theme:
    name: material
    palette:
        - scheme: default
          primary: white
          accent: indigo
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: light blue
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
    # custom_dir: overrides
    features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.expand
    - revision.date
    - revision.history
extra:
    # social:
    #     - icon: material/email
    #       link: mailto:cyruscyliu@gmail.com
    #     - icon: material/file-account
    #       link: Qiang_s_CV.pdf
    #     - icon: simple/googlescholar
    #       link: https://scholar.google.com/citations?user=fa1uB2sAAAAJ&hl=en
    #     - icon: simple/github
    #       link: https://github.com/cyruscyliu
    generator: false
    analytics:
        provider: google
        property: G-KWJ9PWFFMZ
extra_css:
    # - stylesheets/extra.css
    - stylesheets/no-header.css
markdown_extensions:
    - footnotes
    - toc:
        permalink: "#"
        permalink_title: Do what you think is right
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - admonition
    - pymdownx.details
    - pymdownx.superfences
docs_dir: docs
site_name: Le vent se l√®ve ! Il faut tenter de vivre.
site_url: https://github.com/cyruscyliu/cyruscyliu.github.io
plugins:
  - search: { enabled: false }
copyright: "Copyright &copy; 2018 - 2026, Qiang Liu. All rights reserved."